/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pps.view;

import com.hpe.pps.biz.PurchaseBiz;
import com.hpe.pps.biz.PurchaseBizImpl;
import com.hpe.pps.util.FrameUtil;
import com.hpe.pps.util.FrameUtil2;
import com.hpe.pps.vo.ViewPurchase;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author yhy
 */
public class PurchaseOutFrame extends javax.swing.JInternalFrame {
    //引入业务类
    PurchaseBiz pbiz = new PurchaseBizImpl();
    int selectrow = -1;
    /**
     * Creates new form PurchaseOutFrame
     */
    public PurchaseOutFrame() {
        initComponents();
        HiddenCell(this.tblPurchase,1);
        HiddenCell(this.tblPurchase,5);
    }
 public void HiddenCell(JTable table, int column) {
        TableColumn tc = table.getTableHeader().getColumnModel().getColumn(
                column);
        tc.setMaxWidth(0);
        tc.setPreferredWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        table.getTableHeader().getColumnModel().getColumn(column)
                .setMaxWidth(0);
        table.getTableHeader().getColumnModel().getColumn(column)
                .setMinWidth(0);
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        txtConditions = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        dateStart = new com.hpe.pps.util.DateChooserJButton();
        dateEnd = new com.hpe.pps.util.DateChooserJButton();
        txtReturnAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPurid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPurchaseamount = new javax.swing.JTextField();

        setClosable(true);
        setTitle("采购退货");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "采购编号", "商品编号", "商品名", "采购数量", "采购价格", "供应商编号", "供应商", "采购时间"
            }
        ));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPurchase);

        jLabel1.setText("-");

        btnQuery.setText("查询");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        jLabel2.setText("退货数量：");

        btnReturn.setText("采购退货");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel3.setText("采购编号：");

        txtPurid.setEditable(false);

        jLabel4.setText("商品编号：");

        txtPid.setEditable(false);

        jLabel5.setText("采购数量：");

        txtPurchaseamount.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(txtConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuery)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtPurchaseamount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuery)
                    .addComponent(jLabel1)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPurchaseamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
       //按条件查询采购单
        //1获取条件
        String start = this.dateStart.getText();
        String end = this.dateEnd.getText();
        String conditions = this.txtConditions.getText().trim();
        //调用业务
        List<ViewPurchase> list = pbiz.findByCondition(start, end, conditions);
        //显示在表格中
        showOnTable(list);
    }//GEN-LAST:event_btnQueryActionPerformed

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        //选择要退货的商品
        selectrow = this.tblPurchase.getSelectedRow();//selectrow为类属性
        Integer purid = (Integer) this.tblPurchase.getValueAt(selectrow, 0);
        Integer pid = (Integer) this.tblPurchase.getValueAt(selectrow, 1);
        Integer purchaseamount = (Integer) this.tblPurchase.getValueAt(selectrow, 3);
        //显示在文本框
        this.txtPurid.setText(purid.toString());
        this.txtPid.setText(pid.toString());
        this.txtPurchaseamount.setText(purchaseamount.toString());
       
    }//GEN-LAST:event_tblPurchaseMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        if(selectrow == -1){
            JOptionPane.showMessageDialog(this, "请选择要退货的采购单信息");
            return;
        }
        //获取退货信息
        Integer purid = Integer.parseInt(this.txtPurid.getText());
        Integer pid = Integer.parseInt(this.txtPid.getText());
        Integer purchaseamount = Integer.parseInt(this.txtPurchaseamount.getText());
        //获取退货数量
        String sreturnAmount = this.txtReturnAmount.getText();
        //数据验证
        String regex = "[1-9][0-9]*";
        if(sreturnAmount.matches(regex)== false){
            JOptionPane.showMessageDialog(this, "请填写整数");
            return;
        }
        //转换退货数量
        Integer returnAmount = Integer.parseInt(sreturnAmount);
        //判断是否超过采购数量
        if(returnAmount>purchaseamount){
            JOptionPane.showMessageDialog(this, "退货数量大于采购数量");
            return;
        }
       
        //调用业务，改动purchase表，修改退货数量和退货时间
        // purid - returnAmount , 当前时间  采购数量 -退货数量
        // pid   - 库存 int purid, int returnamount, Date returntime, int pid
        java.sql.Date  returntime = new java.sql.Date( new java.util.Date().getTime());
        boolean result = pbiz.purchasereturn(purid,returnAmount,returntime, pid);
        if(result == true){
            JOptionPane.showMessageDialog(this, "退货成功");
            btnQueryActionPerformed(evt);
        }else{
             JOptionPane.showMessageDialog(this, "退货失败");
        }
        //清空文本框
        this.txtPid.setText("");
        this.txtPurid.setText("");
        this.txtPurchaseamount.setText("");
        this.txtReturnAmount.setText("");
        selectrow = -1;
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        //从hashmap中移除
        FrameUtil2.framemap.remove(PurchaseOutFrame.class.getName());
        //FrameUtil.framemap.remove("");
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnReturn;
    private com.hpe.pps.util.DateChooserJButton dateEnd;
    private com.hpe.pps.util.DateChooserJButton dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtConditions;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPurchaseamount;
    private javax.swing.JTextField txtPurid;
    private javax.swing.JTextField txtReturnAmount;
    // End of variables declaration//GEN-END:variables

    private void showOnTable(List<ViewPurchase> list) {
       //1 表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        //2清空表格
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3 添加数据
        for(ViewPurchase pur:list){
            Vector vt = new Vector();
            vt.add(pur.getPurid());//采购编号
            vt.add(pur.getPid());
            vt.add(pur.getPname());
            vt.add(pur.getPurchaseamount());
            vt.add(pur.getPurchaseprice());
            vt.add(pur.getSupplierid());
            vt.add(pur.getSupname());
            vt.add(pur.getPurchasedate());
            dtm.addRow(vt);
            
        }
    }

   
}
