/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-02 09:18:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminjsps.admin.category;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<title>分类列表</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"adminjsps/admin/css/bootstrap.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"adminjsps/admin/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"adminjsps/admin/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"page-header\">\r\n");
      out.write("\t\t<h2 style=\"text-align: center;\">分类列表</h2>\r\n");
      out.write("\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t<caption align=\"right\">\r\n");
      out.write("\t\t\t\t<a  class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/add.jsp\">添加一级分类</a>\r\n");
      out.write("\t\t\t</caption>\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<th>分类名称</th>\r\n");
      out.write("\t\t\t\t<th>描述</th>\r\n");
      out.write("\t\t\t\t<th>操作</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t<td>程序设计</td>\r\n");
      out.write("\t\t\t\t<td>程序设计相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/add2.jsp\">添加二级分类</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/edit.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该一级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除一级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr >\r\n");
      out.write("\t\t\t\t<td>Java Javascript</td>\r\n");
      out.write("\t\t\t\t<td>Java Javascript相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr >\r\n");
      out.write("\t\t\t\t<td>JSP</td>\r\n");
      out.write("\t\t\t\t<td>JSP相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr >\r\n");
      out.write("\t\t\t\t<td>C C++ VC VC++</td>\r\n");
      out.write("\t\t\t\t<td>C C++ VC VC++相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t<td>办公室用书</td>\r\n");
      out.write("\t\t\t\t<td>办公室用书相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/add2.jsp\">添加二级分类</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/edit.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该一级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除一级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr >\r\n");
      out.write("\t\t\t\t<td>微软Office</td>\r\n");
      out.write("\t\t\t\t<td>微软Office相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr >\r\n");
      out.write("\t\t\t\t<td>计算机初级入门</td>\r\n");
      out.write("\t\t\t\t<td>计算机初级入门相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t<td>图形 图像 多媒体</td>\r\n");
      out.write("\t\t\t\t<td>图形 图像 多媒体相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><a class=\"btn btn-primary btn-xs active\"\r\n");
      out.write("\t\t\t\t\thref=\"adminjsps/admin/category/add2.jsp\">添加二级分类</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/edit.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该一级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除一级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Photoshop</td>\r\n");
      out.write("\t\t\t\t<td>Photoshop相关分类</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary btn-xs active\" href=\"adminjsps/admin/category/edit2.jsp\">修改</a>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-danger btn-xs active\" onclick=\"return confirm('您是否真要删除该二级分类？')\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:alert('删除二级分类成功！');\">删除</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t    <li><a href=\"#\">&laquo;</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"#\">&raquo;</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
